package dev.kkorolyov.pancake.entity.control;

import java.util.*;

import dev.kkorolyov.pancake.entity.Entity;
import dev.kkorolyov.pancake.input.KeyAction;
import javafx.scene.Scene;

/**
 * An entity controller which responds to keyboard and mouse input.
 */
public class InteractiveEntityController implements EntityController {
	private final Set<KeyAction> keyActions = new LinkedHashSet<>();
	private final Set<Enum<?>> pressedKeys = new HashSet<>();
	
	/**
	 * Constructs a new controller which receives input from key and mouse button events generated by a {@code Scene}.
	 * @param scene scene sending inputs
	 */
	public InteractiveEntityController(Scene scene) {
		scene.setOnKeyPressed(e -> pressedKeys.add(e.getCode()));
		scene.setOnKeyReleased(e -> pressedKeys.remove(e.getCode()));
		scene.setOnMousePressed((e) -> pressedKeys.add(e.getButton()));
		scene.setOnMouseReleased((e) -> pressedKeys.remove(e.getButton()));
	}
	
	/**
	 * Adds a key(s)-action mapping.
	 * @param keyAction new {@code KeyAction}
	 */
	public void addAction(KeyAction keyAction) {
		keyActions.add(keyAction);
	}
		
	@Override
	public void update(Entity entity, float dt) {
		for (KeyAction keyAction : keyActions) {
			Action action = keyAction.activate(pressedKeys, dt);
			if (action != null)
				action.execute(entity);
		}
	}
}
