package dev.kkorolyov.pancake.entity.control;

import java.io.PrintWriter;
import java.util.*;

import dev.kkorolyov.pancake.entity.Entity;
import dev.kkorolyov.simplelogs.Logger;
import dev.kkorolyov.simplelogs.Logger.Level;
import javafx.scene.Scene;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseButton;

/**
 * An entity controller which responds to keyboard and mouse input.
 */
public class InteractiveEntityController implements EntityController {
	private static final Action nullAction = e -> {};
	private static final Logger log = Logger.getLogger(InteractiveEntityController.class.getName(), Level.DEBUG, new PrintWriter(System.err));	// TODO Temp
	
	private final Map<Enum<?>, Action> 	onPressMap = new HashMap<>(),	// Enum to support both KeyCode and MouseButton
																			onReleaseMap = new HashMap<>();
	private final Set<Enum<?>> ignoredKeys = new HashSet<>();	// Ignore secondary press events
	private final Set<Action> actions = new HashSet<>();
	
	/**
	 * Constructs a new controller which receives input from key and mouse button events generated by a {@code Scene}.
	 * @param scene scene sending inputs
	 */
	public InteractiveEntityController(Scene scene) {
		scene.setOnKeyPressed((e) -> {
			KeyCode code = e.getCode();
			if (onPressMap.containsKey(code) && !ignoredKeys.contains(code)) {	// Skip unmapped and ignored keys
				actions.add(onPressMap.get(code));
				ignoredKeys.add(code);
				log.debug("Key pressed: " + code);
			}
		});
		scene.setOnKeyReleased((e) -> {
			KeyCode code = e.getCode();
			if (ignoredKeys.contains(code)) {
				actions.add(onReleaseMap.get(code));
				ignoredKeys.remove(code);
				log.debug("Key released: " + code);
			}
		});
		scene.setOnMousePressed((e) -> {
			MouseButton code = e.getButton();
			if (onPressMap.containsKey(code) && !ignoredKeys.contains(code)) {	// Skip unmapped and ignored keys
				actions.add(onPressMap.get(code));
				ignoredKeys.add(code);
				log.debug("Mouse pressed: " + code);
			}
		});
		scene.setOnMouseReleased((e) -> {
			MouseButton code = e.getButton();
			if (ignoredKeys.contains(code)) {
				actions.add(onReleaseMap.get(code));
				ignoredKeys.remove(code);
				log.debug("Mouse released: " + code);
			}
		});
	}
	
	/**
	 * Adds a key-action mapping.
	 * @param key pressed key
	 * @param onPress action invoked on key press
	 * @param onRelease action invoked on key release
	 */
	public void addAction(KeyCode key, Action onPress, Action onRelease) {
		onPressMap.put(key, onPress == null ? nullAction : onPress);
		onReleaseMap.put(key, onRelease == null ? nullAction : onRelease);
	}
	/**
	 * Adds a mouse button-action mapping.
	 * @param button pressed button
	 * @param onPress action invoked on button press
	 * @param onRelease action invoked on key release
	 */
	public void addAction(MouseButton button, Action onPress, Action onRelease) {
		onPressMap.put(button, onPress == null ? nullAction : onPress);
		onReleaseMap.put(button, onRelease == null ? nullAction : onRelease);
	}
	
	@Override
	public void update(Entity entity) {
		for (Action action : actions)
			action.execute(entity);
		actions.clear();
	}
}
