package dev.kkorolyov.pancake.component;

import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

import dev.kkorolyov.pancake.Component;
import dev.kkorolyov.pancake.input.KeyAction;

/**
 * An entity controller which responds to keyboard and mouse input.
 */
public class Input implements Component {
	private final Set<KeyAction> keyActions = new LinkedHashSet<>();

	/**
	 * Constructs a new controller which receives input from key and mouse button events generated by a {@code Scene}.
	 * @param keyActions actions to listen for
	 */
	public Input(KeyAction... keyActions) {
		this(Arrays.asList(keyActions));
	}
	/**
	 * Constructs a new controller which receives input from key and mouse button events generated by a {@code Scene}.
	 * @param keyActions actions to listen for
	 */
	public Input(Iterable<KeyAction> keyActions) {
		setActions(keyActions);
	}

	/** @return registered key actions */
	public Iterable<KeyAction> getActions() {
		return keyActions;
	}

	/**
	 * Sets actions occurring on various key combinations.
	 * @param keyActions actions to listen for
	 */
	public void setActions(KeyAction... keyActions) {
		setActions(Arrays.asList(keyActions));
	}/**
	 * Sets actions occurring on various key combinations.
	 * @param keyActions actions to listen for
	 */
	public void setActions(Iterable<KeyAction> keyActions) {
		this.keyActions.clear();

		if (keyActions != null) {
			for (KeyAction action : keyActions) {
				this.keyActions.add(action);
			}
		}
	}
}
