package dev.kkorolyov.pancake.core.component;

import dev.kkorolyov.pancake.core.input.Handler;
import dev.kkorolyov.pancake.platform.entity.Component;

import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * An entity controller which responds to keyboard and mouse input.
 */
public class Input implements Component {
	private final Set<Handler> handlers = new LinkedHashSet<>();
	private boolean facesCursor;

	/**
	 * Constructs a new controller which receives input from key and mouse button events generated by a {@code Scene}.
	 * @param facesCursor whether this controller should request that its containing entity faces the mouse cursor
	 * @param handlers actions to listen for
	 */
	public Input(boolean facesCursor, Handler... handlers) {
		this(facesCursor, Arrays.asList(handlers));
	}
	/**
	 * Constructs a new controller which receives input from key and mouse button events generated by a {@code Scene}.
	 * @param facesCursor whether this controller should request that its containing entity faces the mouse cursor
	 * @param keyActions actions to listen for
	 */
	public Input(boolean facesCursor, Iterable<Handler> keyActions) {
		setFacesCursor(facesCursor);
		setActions(keyActions);
	}

	/** @return registered handlers */
	public Iterable<Handler> getHandlers() {
		return handlers;
	}

	/**
	 * Clears existing actions before applying new {@code keyActions}.
	 * @param handlers actions to listen for
	 */
	public void setActions(Handler... handlers) {
		setActions(Arrays.asList(handlers));
	}
	/**
	 * Clears existing actions before applying new {@code keyActions}.
	 * @param keyActions actions to listen for
	 */
	public void setActions(Iterable<Handler> keyActions) {
		handlers.clear();

		keyActions.forEach(handlers::add);
	}

	/** @return whether this controller requests that its containing entity faces the mouse cursor */
	public boolean facesCursor() {
		return facesCursor;
	}
	/** @param facesCursor if {@code true}, this controller requests that its containing entity faces the mouse cursor */
	public void setFacesCursor(boolean facesCursor) {
		this.facesCursor = facesCursor;
	}
}
