@startuml

package dev.kkorolyov.pancake.skillet {
	class Skillet {
		save()
		load()
		reload()
	}

	package data {
		abstract class DataObservable<T> {
		}
		interface DataChangeListener {
		}

		class Entity {
		}
		class Component {
		}
		class Attribute {
			Object value
		}

		DataObservable o-l- "*" DataChangeListener

		DataObservable <|-d- Entity
		DataObservable <|-d- Component
		DataObservable <|-d- Attribute

		Entity *-- "*" Component
		Component *-- "*" Attribute
	}

	package display {
  	interface Display {
    	Node getRoot()
    }

    class EntityDisplay {
    }
    class ComponentDisplay {
    }
    class AttributeDisplay {
    }

    interface DisplayStrategy {
    	Node display(Attribute)
    }
    DisplayStrategy <|.. NumberDisplayStrategy
    DisplayStrategy <|.. TextDisplayStrategy
    DisplayStrategy <|.. ImageDisplayStrategy
    DisplayStrategy <|.. MapDisplayStrategy

    Display <|.d. EntityDisplay
		Display <|.d. ComponentDisplay
		Display <|.d. AttributeDisplay

		AttributeDisplay *-- "1" DisplayStrategy
  }

  package utility {
  	class UIDecorator {
  	}
  }

  DataChangeListener <|.d. EntityDisplay
	DataChangeListener <|.d. ComponentDisplay
	DataChangeListener <|.d. AttributeDisplay

  EntityDisplay o-- "1" Entity
  ComponentDisplay o-- "1" Component
  AttributeDisplay o-- "1" Attribute

  Skillet --> EntityDisplay
}

@enduml
