name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validateWrapper:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: check
        uses: gradle/actions/wrapper-validation@v3

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 21 ]

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: publish-gradle
        uses: kkorolyov/publish-gradle@0.4.1
        with:
          java-version: ${{ matrix.version }}
          publish-branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
