name: dependencies

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  submitDependencies:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - id: dependencies
        uses: gradle/actions/dependency-submission@v4
