name: dependencies

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  submitDependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 21

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin

      - id: dependencies
        uses: gradle/actions/dependency-submission@v4
