name: docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 21

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin
      - id: gradle
        uses: gradle/actions/setup-gradle@v4

      - id: generate
        shell: bash
        run: ./gradlew allDocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: build/docs
          github_token: ${{ secrets.GITHUB_TOKEN }}

