name: docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - id: gradle
        uses: gradle/actions/setup-gradle@v3

      - id: generate
        shell: bash
        run: ./gradlew allDocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: build/docs
          github_token: ${{ secrets.GITHUB_TOKEN }}

