name: release

on:
  pull_request_target:
    types:
      - closed

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - id: bump
        uses: zwaldowski/match-label-action@v5
        with:
          allowed: major, minor, patch
          default_match: "none"
      - id: version
        if: ${{ steps.bump.outputs.match != 'none' }}
        uses: zwaldowski/semver-release-action@v4
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: version
    if: ${{ needs.version.outputs.version }}

    strategy:
      matrix:
        version:
          - 21

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin
      - id: gradle
        uses: gradle/actions/setup-gradle@v4

      - id: publish
        shell: bash
        run: ./gradlew publish -Pversion=${{ needs.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs:
      - version
      - publish

    steps:
      - id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.version }}
          generate_release_notes: true
