name: renovate

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - id: token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.BUMPBOT_ID }}
          private-key: ${{ secrets.BUMPBOT_KEY }}

      - id: checkout
        uses: actions/checkout@v6

      - id: renovate
        uses: renovatebot/github-action@v46.1.13
        with:
          token: ${{ steps.token.outputs.token }}
        env:
          RENOVATE_PLATFORM_COMMIT: enabled
          RENOVATE_REPOSITORIES: kkorolyov/pancake
          LOG_LEVEL: debug
