name: upgrade wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  upgradeWrapper:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 17 ]

    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin

      - id: gradle
        uses: gradle/gradle-build-action@v2

      - id: git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - id: upgrade
        run: ./gradlew upgradeGradleWrapperAll
